// <auto-generated />
namespace Sort.Tests
{
    using NUnit.Framework;

    /// <summary>
    /// Class for testing
    /// </summary>
    [TestFixture]
    public class SortTests
    {
        /// <summary>
        /// Method for test sorting
        /// </summary>
        /// <param name="array">initial array</param>
        /// <returns>sort array</returns>
        [TestCase(new int[] { 4, 3, 0, 25, 15, 27 }, Result = new int[] { 0, 3, 4, 15, 25, 27 })]
        [TestCase(new int[] { 47, 1, 4, 6, -3, -6, 43, 10, -3, 0 }, Result = new int[] { -6, -3, -3, 0, 1, 4, 6, 10, 43, 47})]
        public int[] Quick_Sort_Test(int[] array)
        {
            QuickSorter.QuickSort(array);
            return array;
        }

        /// <summary>
        /// Method for test sorting
        /// </summary>
        /// <param name="array">initial array</param>
        /// <returns>sort array</returns>
        [TestCase(new int[] { 4, 3, 0, 25, 15, 27 }, Result = new int[] { 0, 3, 4, 15, 25, 27 })]
        [TestCase(new int[] { 47, 1, 4, 6, -3, -6, 43, 10, -3, 0 }, Result = new int[] { -6, -3, -3, 0, 1, 4, 6, 10, 43, 47 })]
        public int[] Merge_Sort_Test(int[] array)
        {
            MergeSorter.MergeSort(array);
            return array;
        }
    }
}