// <auto-generated />
namespace NumbersInserter
{
    using System;

    public class InsertingNumbers
    {
        /// <summary>
        /// Insert one number to another
        /// </summary>
        /// <param name="num1">first number</param>
        /// <param name="num2">second number</param>
        /// <param name="i">start of ranger</param>
        /// <param name="j">end of range</param>
        /// <returns>New number</returns>
        public static int InsertNumber(int num1, int num2, int i, int j)
        {
            if (i < 0 || j < 0 || i > 31 || j > 31)
            {
                throw new ArgumentOutOfRangeException();
            }

            if (i > j)
            {
                throw new ArgumentException();
            }

            int medium = ((2 << (j - i)) - 1) << i;
            return (num1 & ~medium) | ((num2 << i) & medium);
        }
    }
}
