//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.DataBase.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountType
    {
       
        public AccountType()
        {
            this.Account = new HashSet<Account>();
        }
    
        public string AccountType1 { get; set; }
        public int AccountTypeId { get; set; }
    
       
        public virtual ICollection<Account> Account { get; set; }
    }
}
