//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.DataBase.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string AccountId { get; set; }
        public decimal Amount { get; set; }
        public int Points { get; set; }
        public Nullable<int> AccountOwnerId { get; set; }
        public Nullable<int> AccountTypeId { get; set; }
    
        public virtual AccountOwner AccountOwner { get; set; }
        public virtual AccountType AccountType { get; set; }
    }
}
